blank_issues_enabled: false

contact_links:

* name: Security Report
  url: mailto:tech@amaanitvam.org
  about: Report security vulnerabilities privately.

* name: General Discussion
  url: https://www.amaanitvam.org
  about: General questions and discussions.
